In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = sns.load_dataset('penguins')
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [3]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [5]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [8]:
df.head(3)

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female

In [9]:
from sklearn.preprocessing import LabelEncoder
my_var = LabelEncoder()
df['species'] = my_var.fit_transform(df['species'])
df['island'] = my_var.fit_transform(df['island'])
df['sex'] = my_var.fit_transform(df['sex'])

df.head(3)

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        0       2            39.1           18.7              181.0   
1        0       2            39.5           17.4              186.0   
2        0       2            40.3           18.0              195.0   

   body_mass_g  sex  
0       3750.0    1  
1       3800.0    0  
2       3250.0    0

In [10]:
df1 = df.copy()
df1.head(1)

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        0       2            39.1           18.7              181.0   

   body_mass_g  sex  
0       3750.0    1

In [11]:
#Using For Loop

my_obj = ['species', 'island', 'sex']

for v in my_obj:
    
    
    from sklearn.preprocessing import LabelEncoder
    my_var1 = LabelEncoder()
    df1[v] = my_var1.fit_transform(df1[v])
    
df1.head(1)    



species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        0       2            39.1           18.7              181.0   

   body_mass_g  sex  
0       3750.0    1

In [12]:
df.drop('species', axis =1, inplace=True)
df.head(1)

island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  sex
0       2            39.1           18.7              181.0       3750.0    1

In [13]:
Y = df1['species']
Y.head()

0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

In [14]:
X = df.copy()

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=8, criterion= 'gini', random_state=0)
rf_model = rf.fit(X_train, Y_train)

In [16]:
y_pred = rf_model.predict(X_test)
y_pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2], dtype=int64)

In [17]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, accuracy_score

accuracy = accuracy_score(Y_test, y_pred)
print(accuracy)

0.98


In [18]:
cm = confusion_matrix(Y_test, y_pred)
print(cm)

[[48  0  0]
 [ 2 14  0]
 [ 0  0 36]]


In [19]:
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        48
           1       1.00      0.88      0.93        16
           2       1.00      1.00      1.00        36

    accuracy                           0.98       100
   macro avg       0.99      0.96      0.97       100
weighted avg       0.98      0.98      0.98       100



In [20]:
# import pickle
# pickle.dump(rf_model, open('rf_model.pkl', 'wb'))

In [21]:
# saved_model = pickle.load(open('rf_model.pkl', 'rb'))

In [25]:
# filepath = r'C:/Users/chinm/OneDrive/Desktop/ML_models/rf_model.pkl'
# pickle.dump(rf_model, open(filepath, 'wb'))